baseurl = "https://www.sjm.io/"
languageCode = "en-gb"
title = "Simon Morgan"
theme = "hyde"

[params]
  description = "I Conjure the Spirits of the Computer with My Spells"
  googleAnalytics = "UA-66871655-2"

[Menus]
  main = [
    {Name = "About", URL = "/about/"},
    {Name = "Posts", URL = "/post/"},
    {Name = "Categories", URL = "/categories/"},
    {Name = "Tags", URL = "/tags/"},
  ]
