title = "Simon Morgan"
theme = "kiera"
copyright = "Copyright &copy; Simon Morgan"

pygmentsCodeFences = true

googleAnalytics = "UA-66871655-2"

[author]
    name = "Simon Morgan"
    github = "drguildo"
    twitter = "drguildo"
